### ISSUE TITLE
parsing bug in media.php 

### ISSUE THREAD

**Issue by frank16** [oakesville/mythling#42] opened 2015-04-02 10:01 UTC
When a video filename has multiple '.' symbols, the 'type'  gets messed up, something like "donald.duck.avi"

**Comment by oakesville** [comment] 2015-04-03 00:48
Yes, I can confirm that this definitely is a Mythling Services parsing bug in media.php.  I'll fix this as soon as possible on the 1.2 branch.  Luckily since it's isolated to media.php, the fix can be retrofitted to Mythling 1.1.

Thanks,
 - Don

**Comment by oakesville** [comment] 2015-04-04 01:39
Fixed on branch rel-1.2.

**Closed by oakesville** 2015-04-04 01:39 UTC
Labels: bug
